### ISSUE TITLE
BLAS/LAPACK linked libraries not delivered in build variants

### ISSUE THREAD

**Issue by mfansler** [conda-forge/r-base-feedstock#270] opened 2023-08-02 14:01 UTC
The [recent workaround](https://github.com/conda-forge/r-base-feedstock/pull/262) to preserve backward compatibility for **osx-arm64** leads to symlinks that are overly-specific:

E.g., here are the files in `lib/R/lib/` for `r-base=4.3.1=h8babed3_3`:

```
% ls -lh
total 6000
-rwxrwxr-x  2 mfansler  staff   2.9M Jul 21 06:18 libR.dylib
lrwxr-xr-x  1 mfansler  staff    25B Aug  2 09:47 libRblas.dylib -> ../../libblas.3.9.0.dylib
lrwxr-xr-x  1 mfansler  staff    27B Aug  2 09:47 libRlapack.dylib -> ../../liblapack.3.9.0.dylib
```

However, the `libblas` and `liblapack` packages only deliver this for the Netlib builds. Should probably loosen the symlink to point only to `../../libblas.dylib`, without a version specification.

The effects of this are reported in https://github.com/conda-forge/r-matrix-feedstock/issues/35 (with fully documented example).

**Comment by isuruf** [comment] 2023-09-20 23:00
Is this issue still there?

**Comment by mfansler** [comment] 2023-09-21 03:11
I'm not seeing the problem with `r-matrix` anymore, but `r-kernsmooth` will throw it (as [mentioned here](https://github.com/conda-forge/r-matrix-feedstock/issues/35#issuecomment-1728450956)):

```bash
$ R

R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: aarch64-apple-darwin20.0.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(KernSmooth)
Error: package or namespace load failed for ‘KernSmooth’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/mfansler/mambaforge-arm64/envs/foo/lib/R/library/KernSmooth/libs/KernSmooth.dylib':
  dlopen(/Users/mfansler/mambaforge-arm64/envs/foo/lib/R/library/KernSmooth/libs/KernSmooth.dylib, 0x0006): Library not loaded: @rpath/R/lib/libRblas.dylib
  Referenced from: <C6331581-708C-38EF-8386-DDB62149BA5D> /Users/mfansler/mambaforge-arm64/envs/foo/lib/R/library/KernSmooth/libs/KernSmooth.dylib
  Reason: tried: '/Users/mfansler/mambaforge-arm64/envs/foo/lib/R/library/KernSmooth/libs/../../../lib/R/lib/libRblas.dylib' (no such file), '/Users/mfansler/mambaforge-arm64/envs/foo/lib/R/library/KernSmooth/libs/../../../../R/lib/libRblas.dylib' (no such file), '/Users/mfansler/mambaforge-arm64/envs/foo/lib/R/library/KernSmooth/libs/../../../lib/R/lib/libRblas.dylib' (no such file), '/Users/mfansler/mambaforge-arm64/envs/foo/lib/R/library/KernSmooth/libs/../../../.
```

## Environment
<details>

```bash
$ mamba list
# packages in environment at /Users/mfansler/mambaforge-arm64/envs/foo:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.1               anacondar_1    conda-forge
blas                      2.118                accelerate    conda-forge
blas-devel                3.9.0           18_osxarm64_accelerate    conda-forge
bwidget                   1.9.14               hce30654_1    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.19.1               hb547adb_0    conda-forge
ca-certificates           2023.7.22            hf0a4a13_0    conda-forge
cairo                     1.16.0            hc5b65c1_1017    conda-forge
cctools_osx-arm64         973.0.1             h62378fb_14    conda-forge
clang                     16.0.6               he79909e_1    conda-forge
clang-16                  16.0.6          default_h07b2d96_1    conda-forge
clang_osx-arm64           16.0.6               hc421ffc_1    conda-forge
clangxx                   16.0.6          default_h298e243_1    conda-forge
clangxx_osx-arm64         16.0.6               hcd7bac0_1    conda-forge
compiler-rt               16.0.6               hf8d1dfb_0    conda-forge
compiler-rt_osx-arm64     16.0.6               hf8d1dfb_0    conda-forge
curl                      8.3.0                hc52a3a8_0    conda-forge
expat                     2.5.0                hb7217d7_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h82840c6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hadb7bae_2    conda-forge
fribidi                   1.0.10               h27ca646_0    conda-forge
gettext                   0.21.1               h0186832_0    conda-forge
gfortran_impl_osx-arm64   12.3.0               hbbb9e1e_1    conda-forge
gfortran_osx-arm64        12.3.0               h57527a5_1    conda-forge
gmp                       6.2.1                h9f76cd9_0    conda-forge
graphite2                 1.3.13            h9f76cd9_1001    conda-forge
gsl                       2.7                  h6e638da_0    conda-forge
harfbuzz                  8.2.1                hf1a6348_0    conda-forge
icu                       73.2                 hc8870d7_0    conda-forge
isl                       0.25                 h9a09cb3_0    conda-forge
krb5                      1.21.2               h92f50d5_0    conda-forge
ld64_osx-arm64            609                 ha4bd21c_14    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libblas                   3.9.0           18_osxarm64_accelerate    conda-forge
libcblas                  3.9.0           18_osxarm64_accelerate    conda-forge
libclang-cpp16            16.0.6          default_h07b2d96_1    conda-forge
libcurl                   8.3.0                hc52a3a8_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libdeflate                1.19                 hb547adb_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_1    conda-forge
libgfortran-devel_osx-arm64 12.3.0               hc62be1c_1    conda-forge
libgfortran5              13.2.0               hf226fd6_1    conda-forge
libglib                   2.78.0               h24e9cb9_0    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libjpeg-turbo             2.1.5.1              hb547adb_1    conda-forge
liblapack                 3.9.0           18_osxarm64_accelerate    conda-forge
liblapacke                3.9.0           18_osxarm64_accelerate    conda-forge
libllvm16                 16.0.6               he79909e_2    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libopenblas               0.3.24          openmp_hd76b1f2_0    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libtiff                   4.6.0                h77c4dce_1    conda-forge
libwebp-base              1.3.2                hb547adb_0    conda-forge
libxml2                   2.11.5               h25269f3_1    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
llvm-openmp               16.0.6               h1c12783_0    conda-forge
llvm-tools                16.0.6               he79909e_2    conda-forge
make                      4.3                  he57ea6c_1    conda-forge
mpc                       1.3.1                h91ba8db_0    conda-forge
mpfr                      4.2.0                he09a6ba_0    conda-forge
ncurses                   6.4                  h7ea286d_0    conda-forge
openssl                   3.1.3                h53f4e23_0    conda-forge
pango                     1.50.14              hcf40dda_2    conda-forge
pcre2                     10.40                hb34f9b4_0    conda-forge
pixman                    0.40.0               h27ca646_0    conda-forge
r-base                    4.3.1                h8ca35e0_4    conda-forge
r-kernsmooth              2.23_22           r43hf85d023_0    conda-forge
r-lattice                 0.21_8            r43h21dc0da_1    conda-forge
r-matrix                  1.6_1             r43hdce2eb6_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
sigtool                   0.1.3                h44b9a77_0    conda-forge
tapi                      1100.0.11            he4954df_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
tktable                   2.10                 hd996620_3    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
zlib                      1.2.13               h53f4e23_5    conda-forge
zstd                      1.5.5                h4f39d0f_0    conda-forge
```

</details>

## Linking

```bash
$ otool -L $CONDA_PREFIX/lib/R/library/KernSmooth/libs/KernSmooth.dylib
/Users/mfansler/mambaforge-arm64/envs/foo/lib/R/library/KernSmooth/libs/KernSmooth.dylib:
	@rpath/R/library/KernSmooth/libs/KernSmooth.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/R/lib/libRblas.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
	@rpath/R/lib/libR.dylib (compatibility version 4.3.0, current version 4.3.0)

$ ls -lh $CONDA_PREFIX/lib/R/lib/     
total 6000
-rwxrwxr-x  2 mfansler  staff   2.9M Sep 14 13:01 libR.dylib
lrwxr-xr-x  1 mfansler  staff    25B Sep 20 22:40 libRblas.dylib -> ../../libblas.3.9.0.dylib
lrwxr-xr-x  1 mfansler  staff    27B Sep 20 22:40 libRlapack.dylib -> ../../liblapack.3.9.0.dylib
```

**Comment by LouisFaure** [comment] 2024-01-24 21:49
the issue is still present as of today, as @mfansler, changing the symlink to point only to ../../libblas.dylib is fixing it. Would be nice to have it working without renaming these links manually...

**Comment by mfansler** [comment] 2024-01-24 22:52
@LouisFaure would you mind adding specifics for how you encounter this? (e.g., minimal environment and code)

**Comment by LouisFaure** [comment] 2024-01-24 23:17
I can reproduce this issue (miniforge arm64 on apple silicon) with the following:
```bash
mamba create -n r-base_test r-kernsmooth -y
mamba activate r-base_test
Rscript -e 'library(KernSmooth)'
```

This will lead to the same `dyn.load` error.

Checking `file $CONDA_PREFIX/lib/R/lib/libRblas.dylib` and `file $CONDA_PREFIX/lib/R/lib/libRlapack.dylib` will both throw a "broken symbolic link to" the libs to a version 3.9.0.

To manually fix these, I run:
```bash
cp $CONDA_PREFIX/lib/liblapack.3.dylib $CONDA_PREFIX/lib/liblapack.3.9.0.dylib
cp $CONDA_PREFIX/lib/libblas.3.dylib $CONDA_PREFIX/lib/libblas.3.9.0.dylib
Rscript -e 'library(KernSmooth)'
```


Although using netlib as backend solves it, I think the default install should be fixed, this would prevent many people from spending a long time figuring out this dynamic library issue!

<details><summary>details</summary>
<p>

```bash
# packages in environment at /Users/faurel1/miniforge3/envs/r-base_test:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.1               anacondar_1    conda-forge
bwidget                   1.9.14               hce30654_1    conda-forge
bzip2                     1.0.8                h93a5062_5    conda-forge
c-ares                    1.25.0               h93a5062_0    conda-forge
ca-certificates           2023.11.17           hf0a4a13_0    conda-forge
cairo                     1.18.0               hd1e100b_0    conda-forge
cctools_osx-arm64         973.0.1             h998149b_15    conda-forge
clang                     17.0.6               haab561b_2    conda-forge
clang-17                  17.0.6          default_hd209bcb_2    conda-forge
clang_impl_osx-arm64      17.0.6               he47c785_8    conda-forge
clang_osx-arm64           17.0.6               h54d7cd3_8    conda-forge
clangxx                   17.0.6          default_h5c94ee4_2    conda-forge
clangxx_impl_osx-arm64    17.0.6               h50f59cd_8    conda-forge
clangxx_osx-arm64         17.0.6               h54d7cd3_8    conda-forge
compiler-rt               17.0.6               h3808999_1    conda-forge
compiler-rt_osx-arm64     17.0.6               h3808999_1    conda-forge
curl                      8.5.0                h2d989ff_0    conda-forge
expat                     2.5.0                hb7217d7_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               h82840c6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hadb7bae_2    conda-forge
fribidi                   1.0.10               h27ca646_0    conda-forge
gettext                   0.21.1               h0186832_0    conda-forge
gfortran_impl_osx-arm64   12.3.0               h53ed385_2    conda-forge
gfortran_osx-arm64        12.3.0               h57527a5_1    conda-forge
gmp                       6.3.0                h965bd2d_0    conda-forge
graphite2                 1.3.13            h9f76cd9_1001    conda-forge
harfbuzz                  8.3.0                h8f0ba13_0    conda-forge
icu                       73.2                 hc8870d7_0    conda-forge
isl                       0.26            imath32_h347afa1_101    conda-forge
krb5                      1.21.2               h92f50d5_0    conda-forge
ld64_osx-arm64            609                 h6a44367_15    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libblas                   3.9.0           21_osxarm64_openblas    conda-forge
libclang-cpp17            17.0.6          default_hd209bcb_2    conda-forge
libcurl                   8.5.0                h2d989ff_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libdeflate                1.19                 hb547adb_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h93a5062_2    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_2    conda-forge
libgfortran-devel_osx-arm64 12.3.0               hc62be1c_2    conda-forge
libgfortran5              13.2.0               hf226fd6_2    conda-forge
libglib                   2.78.3               hb438215_0    conda-forge
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libjpeg-turbo             3.0.0                hb547adb_1    conda-forge
liblapack                 3.9.0           21_osxarm64_openblas    conda-forge
libllvm17                 17.0.6               haab561b_1    conda-forge
libnghttp2                1.58.0               ha4dd798_1    conda-forge
libopenblas               0.3.26          openmp_h6c19121_0    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libtiff                   4.6.0                ha8a6c65_2    conda-forge
libwebp-base              1.3.2                hb547adb_0    conda-forge
libxml2                   2.12.4               h0d0cfa8_1    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
llvm-openmp               17.0.6               hcd81f8e_0    conda-forge
llvm-tools                17.0.6               haab561b_1    conda-forge
make                      4.3                  he57ea6c_1    conda-forge
mpc                       1.3.1                h91ba8db_0    conda-forge
mpfr                      4.2.1                h9546428_0    conda-forge
ncurses                   6.4                  h463b476_2    conda-forge
openssl                   3.2.0                h0d3ecfb_1    conda-forge
pango                     1.50.14              hcf40dda_2    conda-forge
pcre2                     10.42                h26f9a81_0    conda-forge
pixman                    0.43.0               hebf3989_0    conda-forge
r-base                    4.3.2                h9389748_1    conda-forge
r-kernsmooth              2.23_22           r43hf85d023_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
sigtool                   0.1.3                h44b9a77_0    conda-forge
tapi                      1100.0.11            he4954df_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tktable                   2.10                 hd996620_5    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
zlib                      1.2.13               h53f4e23_5    conda-forge
zstd                      1.5.5                h4f39d0f_0    conda-forge
```
</p>
</details>

**Comment by isuruf** [comment] 2024-06-27 23:26
Fixed in #318

**Closed by isuruf** 2024-06-27 23:26 UTC
Labels: bug

**Comment by skwde** [comment] 2026-03-03 05:35
@mfansler thanks for your response.

This time, I have seen it with `r-base=4.3.3` and `KernSmooth@2.23-22` (via `r-renv=1.1.5`).

Though I experienced also with other versions in the past.

**Comment by mfansler** [comment] 2026-03-10 07:12
@skwde all builds were built against and depend on BLAS, just that some other R dependencies expect to specifically find the (unnecessary) libR{blas,lapack}.so, and the earlier builds are missing that. So, it's not a matter of specifying BLAS.
