### ISSUE TITLE
Pending changes to defaults r-base packages

### ISSUE THREAD

**Issue by kalefranz** [conda-forge/r-base-feedstock#34] opened 2018-02-12 20:08 UTC
The `r-base` packages in the `r` channel and in https://repo.continuum.io/pkgs/r will be patched in the coming days to make room for the addition of MRO packages to the channel.  The central problem is that we need to provide exclusivity between the `r-base` package and an `mro-base` package; they cannot be installed into the same environment, due to overlapping paths.

We've considered *many* technical solutions to this problem, including changes to conda, and we've arrived at the solution that requires us to patch metadata of the `r-base` package.  Specifically, we have to add one additional dependency--a package that allows us to enforce the exclusivity.

Specifically, we're adding an additional package to the `r` channel with the following `meta.yaml`

```
package:
  name: _r-mutex
  version: 1.0.0

build:
  string: anacondar_1
  number: 1
  track_features:
    - anacondar

about:
  license: BSD
  summary: A mutex package to ensure environment exclusivity between Anaconda R and MRO.
```

(There's a similar `_r-mutex` package that we're using for mro, just with a different build string.)

All `r-base` packages will now include, or be patched to include

    "_r-mutex 1.* anacondar_1"

in the depends list.

Without this step, users will often end up with both `r-base` and `mro-base` installed in the same environment.

For the `r` channel, I'm working on a script that will just download the package, patch the metadata, and then re-upload the package in place.  We're doing this with the understanding that it *will* change the md5 of the package, and so it could raise alarms for people mirroring repositories.  It's the least bad of all the alternatives we have right now though.

If the conda-forge community wants to use my script, I'll be happy to share it.

If instead the community wants to take the route of just rebuilding the packages, it'll be necessary to remove the `main` tag on anaconda.org from any `r-base` packages without `"_r-mutex 1.* anacondar_1"` in the dependency list.

We'll likely be releasing the MRO packages in the `r` and https://repo.continuum.io/pkgs/r `defaults` channel early next week.

**Comment by jdblischak** [comment] 2018-02-26 15:18
@conda-forge/r-base Do we have a plan for updating the conda-forge R packages?

**Comment by isuruf** [comment] 2018-02-27 15:21
cc @conda-forge/core

**Comment by bgruening** [comment] 2018-02-27 16:28
I can not say much to this other than I trust you guys to take the right decision there and I would welcome to align defaults and conda-forge more and not less. So I assume patching ours is ok for me. I don't have permissions to do it.

My plan for updating R on conda-forge was to wait until R 3.5.1, but the only reason was the overhead that this is creating for our CI systems and man power we need to invest. If both is not a concern for you guys I'm fine with also updating to 3.4.3.

I'm quite disappointed by R that we really need to re-build for every minor release all packages and I'm not seeing much benefits in this.

> We'll likely be releasing the MRO packages in the r and https://repo.continuum.io/pkgs/r defaults channel early next week.

@kalefranz any reason you upload it to both channels. Why are there still two channels under `defaults`?

**Comment by jakirkham** [comment] 2018-02-27 17:09
> I don't have permissions to do it.

Is there something you need permissions for in the R stack, @bgruening? Happy to merge any maintainer PRs that would help.

**Comment by jdblischak** [comment] 2018-02-28 19:53
If we need to do a mass upgrade of the conda-forge R packages to add this new depdency, would it be possible to combine this with [updating the recipes for conda-build 3](https://github.com/conda-forge/conda-build-feedstock/pull/30#issuecomment-369357481) and dropping support for R 3.3.2 (#36)? This would minimize the strain on the CI systems.

**Comment by isuruf** [comment] 2018-02-28 19:55
I think it's easier to use @kalefranz's script and fix the conda-forge packages. What do you think?

**Comment by jdblischak** [comment] 2018-02-28 20:14
> I think it's easier to use @kalefranz's script and fix the conda-forge packages. What do you think?

@isuruf I'm not sure why that would be easier. If I understand correctly, that strategy only modifies the package metadata on Anaconda Cloud, but won't update the recipes in the feedstocks. If we are already going to have to update all the feedstock recipes to be cb3 compliant, we could also add the dependency then.

And these options don't have to be mutually exclusive. We could use the script to modify the packages to quickly update everything. And then the recipes in the feedstocks would be updated later when migrating to cb3. Either way I only have access to the feedstocks. If we decide to run @kalefranz's script, someone with permission to directly edit the conda-forge Anaconda Cloud packages would have to do this.

**Comment by isuruf** [comment] 2018-02-28 20:16
Sure. Btw, we don't have to update the recipes in the feedstocks if we use script to modify the packages in anaconda cloud.  Just the r-base package with `run_exports`

**Comment by jdblischak** [comment] 2018-02-28 20:36
> we don't have to update the recipes in the feedstocks if we use script to modify the packages in anaconda cloud. Just the r-base package with run_exports

Got it. Thanks for the explanation. I just re-read the [blog post on conda-build 3](https://www.anaconda.com/blog/developer-blog/package-better-conda-build-3/) to remind myself of the new features like `run_exports`.

**Comment by jdblischak** [comment] 2018-05-02 02:02
What's the status of this issue?

**Comment by bgruening** [comment] 2018-05-02 04:07
I'm all for patching the packages. @kalefranz can you do this?

**Comment by jdblischak** [comment] 2018-06-20 02:28
> Without this step, users will often end up with both r-base and mro-base installed in the same environment.

I can confirm this is the current behavior. r-base from conda-forge gets installed (my default channels are conda-forge followed by defaults) in addition to mro-base:

```
conda create -y -n testmro mro-base r-tidyverse -c r
```

> If the conda-forge community wants to use my script, I'll be happy to share it.

@kalefranz Is the script available on GitHub somewhere?

**Comment by elgalu** [comment] 2018-06-27 12:15
I'm currently hitting `UnsatisfiableError`

```
  - _r-mutex=1[build=anacondar_1]
  - mro-base=3.4 -> _r-mutex=1[build=mro_2]
```

Any workaround?

**Comment by elgalu** [comment] 2018-06-27 14:01
Thanks for the quick feedback @jdblischak ! sorry for the lame report, I don't have any preference as long as all these packages get installed in a docker image I'm trying to build for Jupyter notebooks:

https://gist.github.com/elgalu/2f2633780fdcba36e2f6e11d182c8deb

**Comment by jdblischak** [comment] 2018-06-27 14:13
@elgalu My guess is that one of the R packages you are trying to install is available only for r-base and not mro-base. Thus when conda tries to install both r-base and mro-base, it throws this error.

Thus I think you have two options:

1. Determine which of the R packages aren't available for mro-base, and request that the Anaconda team installs them (I don't know where you would do this)
2. Switch to using r-base instead of mro-base

In general, you don't want to mix the defaults and conda-forge channels. They are not compatible (at least for now).

Either way, your issue is with r-base and mro-base from the defaults channel. This GitHub repo is for the conda-forge version of r-base, so there's not much we can do to help here.

**Comment by dhirschfeld** [comment] 2018-06-28 02:05
Currently, having both `conda-forge` and `defaults` in your channels when installing R packages is likely to lead to segfaults or simply installing two different versions in the same environment which then clobber each other.

An example of this problem is given in https://github.com/conda/conda/issues/7459

The advice there was that `conda-forge` need to implement the `_r-mutex` scheme for the channels to be compatible.

...so, just adding my +:100: here as it currently is quite difficult to not accidentally destroy your R environment when running any conda commands

**Comment by jdblischak** [comment] 2018-11-15 20:49
The latest build of R 3.5.1 has the runtime dependency `_r-mutex 1.* anacondar_1` (implemented in PR #61).

@dhirschfeld Could you please test this out?

@conda-forge/r-base I'm not a maintainer, so I can't close this issue. If we're satisfied that this has been addressed, could one of you please close this issue?

**Comment by dhirschfeld** [comment] 2018-11-27 02:46
I just tested the below install plan:
```
conda create -n testr --file .\requirements.txt
```
<details>
<summary><tt>requirements.txt</tt></summary>

```
mro-base
r-broom
r-caret
r-data.table
r-dbi
r-dbplyr
r-devtools
r-doparallel
r-dplyr
r-forcats
r-foreach
r-formatr
r-ggplot2
r-glmnet
r-haven
r-hms
r-httr
r-irkernel
r-iterators
r-jsonlite
r-lubridate
r-magrittr
r-modelr
r-odbc
r-plotly
r-plyr
r-png=0.1_7=mro343_0
r-purrr
r-quantmod
r-randomforest
r-rbokeh
r-readr
r-readxl
r-recommended
r-reshape2
r-reticulate
r-rmarkdown
r-rodbc
r-roxygen2
r-rvest
r-shiny
r-stringr
r-tibble
r-tidyr
r-tidyverse
r-xml2
r-zoo
rpy2
rstudio
```
</details>
<br>

...with both `defaults` and `conda-forge` in my channels and it still appears to install two different versions of R:

```
λ conda list | grep base
mro-base                  3.4.3                         0
r-base                    3.4.1                h8933c1f_8    conda-forge
r-base64enc               0.1_3           mro343h889e2dd_0
r-robustbase              0.93_2           r341h6115d3f_0    conda-forge

λ conda list | grep mutex
_r-mutex                  1.0.0                     mro_2
```

Whilst in this instance it doesn't segfault it's probably highly likely to given the mixing of mro and non-mro packages.

When I run R in than environment I get the 3.4.1 non-mro conda-forge version.

<details>
<summary><tt>λ conda list</tt></summary>

```
# Name                    Version                   Build  Channel
_r-mutex                  1.0.0                     mro_2
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
certifi                   2018.10.15               py36_0
font-ttf-dejavu-sans-mono 2.37                 h6964260_0
font-ttf-inconsolata      2.001                hcb22688_0
font-ttf-source-code-pro  2.030                h7457263_0
font-ttf-ubuntu           0.83                 h8b1ccd4_0
fonts-anaconda            1                    h8fa9717_0
freetype                  2.9.1                ha9979f8_1
icu                       58.2                 ha66f8fd_1
jinja2                    2.10                     py36_0
jpeg                      9c                hfa6e2cd_1001    conda-forge
libpng                    1.6.35               h2a8f88b_0
libssh2                   1.8.0                hd619d38_4
libxcb                    1.13              h301d43c_1002    conda-forge
m2-bash                   4.3.042                       5
m2-gcc-libs               5.3.0                         4
m2-heimdal                1.5.3                        10
m2-heimdal-libs           1.5.3                        10
m2-icu                    56.1                          2
m2-libcrypt               1.3                           2
m2-libdb                  5.3.28                        3
m2-libedit                3.1                    20150326
m2-libopenssl             1.0.2.g                       2
m2-libreadline            6.3.008                       8
m2-libsqlite              3.10.0.0                      2
m2-msys2-runtime          2.5.0.17080.65c939c               3
m2-ncurses                6.0.20160220                  2
m2-openssh                7.1p2                         2
m2-openssl                1.0.2.g                       2
m2-zlib                   1.2.8                         4
m2w64-bwidget             1.9.10                        2
m2w64-bzip2               1.0.6                         6
m2w64-c-ares              1.11.0                        2
m2w64-ca-certificates     20150426                    103
m2w64-curl                7.48.0                        2
m2w64-diffutils           3.3.2                         2
m2w64-expat               2.1.1                         2
m2w64-fftw                3.3.4                         6
m2w64-flac                1.3.1                         3
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-gnutls              3.4.11                        2
m2w64-grep                2.24                          2
m2w64-gsl                 2.1                           2
m2w64-icu                 58.2                 heb44b8b_2
m2w64-jansson             2.7                           3
m2w64-libffi              3.2.1                         4
m2w64-libiconv            1.14                          6
m2w64-libidn              1.32                          4
m2w64-libjpeg-turbo       1.4.2                         3
m2w64-libmetalink         0.1.3                         2
m2w64-libogg              1.3.2                         3
m2w64-libpng              1.6.21                        2
m2w64-libsndfile          1.0.26                        2
m2w64-libssh2             1.7.0                         2
m2w64-libsystre           1.0.1                         3
m2w64-libtasn1            4.7                           2
m2w64-libtiff             4.0.6                         2
m2w64-libtre-git          122.c2f5d13                   5
m2w64-libvorbis           1.3.5                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-libxml2             2.9.3                         4
m2w64-mpfr                3.1.4                         4
m2w64-nettle              3.1.1                         4
m2w64-nghttp2             1.9.2                         2
m2w64-openssl             1.0.2.g                       2
m2w64-p11-kit             0.23.2                        2
m2w64-pcre                8.38                          2
m2w64-rtmpdump-git        499.a107cef                   4
m2w64-speex               1.2rc2                        3
m2w64-speexdsp            1.2rc3                        3
m2w64-tcl                 8.6.5                         3
m2w64-tk                  8.6.5                         3
m2w64-tktable             2.10                          5
m2w64-wineditline         2.101                         5
m2w64-xz                  5.2.2                         2
m2w64-zlib                1.2.8                        10
markupsafe                1.1.0            py36he774522_0
mro-base                  3.4.3                         0
mro-basics                3.4.3                         0
msys2-conda-epoch         20160418                      1
openssl                   1.0.2p               hfa6e2cd_0
pandoc                    2.4                           0    conda-forge
pip                       18.1                     py36_0
pthread-stubs             0.4               h301d43c_1001    conda-forge
python                    3.6.7                h33f27b4_1
pytz                      2018.7                   py36_0
qt                        5.6.2           vc14h6f8c307_12
r-abind                   1.4_5            r341h6115d3f_0    conda-forge
r-assertthat              0.2.0           mro343h889e2dd_0
r-backports               1.1.2           mro343h889e2dd_0
r-base                    3.4.1                h8933c1f_8    conda-forge
r-base64enc               0.1_3           mro343h889e2dd_0
r-bh                      1.66.0_1              r341_1001    conda-forge
r-bindr                   0.1.1            r341h6115d3f_1    conda-forge
r-bindrcpp                0.2.2            r341h6115d3f_1    conda-forge
r-bit                     1.1_12          mro343h889e2dd_0
r-bit64                   0.9_7           mro343h889e2dd_0
r-bitops                  1.0_6                  r3.4.1_2
r-blob                    1.1.1                    r341_1    conda-forge
r-boot                    1.3_20                 mro343_0
r-brew                    1.0_6                  r3.4.1_2
r-broom                   0.5.0            r341h6115d3f_2    conda-forge
r-callr                   3.0.0            r341h6115d3f_0    conda-forge
r-caret                   6.0_80           r341h6115d3f_1    conda-forge
r-catools                 1.17.1.1         r341h6115d3f_2    conda-forge
r-cellranger              1.1.0           mro343h889e2dd_0
r-checkpoint              0.4.3                  mro343_0
r-class                   7.3_14                 mro343_0
r-cli                     1.0.0           mro343h889e2dd_0
r-clipr                   0.4.1            r341h6115d3f_1    conda-forge
r-clisymbols              1.2.0            r341h6115d3f_1    conda-forge
r-cluster                 2.0.6                  mro343_0
r-codetools               0.2_15                 mro343_0
r-colorspace              1.3_2           mro343h889e2dd_0
r-commonmark              1.5              r341h6115d3f_3    conda-forge
r-config                  0.3              r341h6115d3f_1    conda-forge
r-crayon                  1.3.4           mro343h889e2dd_0
r-crosstalk               1.0.0           mro343h889e2dd_0
r-curl                    3.1                    mro343_0
r-cvst                    0.2_2            r341h6115d3f_0    conda-forge
r-data.table              1.11.4           r341h6115d3f_2    conda-forge
r-dbi                     1.0.0            r341h6115d3f_1    conda-forge
r-dbplyr                  1.2.2            r341h6115d3f_1    conda-forge
r-ddalpha                 1.3.4            r341h6115d3f_1    conda-forge
r-deoptimr                1.0_8           mro343h889e2dd_0
r-deployrrserve           9.0.0                  mro343_0
r-desc                    1.2.0            r341h6115d3f_1    conda-forge
r-devtools                2.0.1            r341h6115d3f_0    conda-forge
r-digest                  0.6.18           r341h6115d3f_0    conda-forge
r-dimred                  0.1.0           mro343h889e2dd_0
r-doparallel              1.0.12                 mro343_0
r-dplyr                   0.7.6            r341h6115d3f_1    conda-forge
r-drr                     0.0.3            r341h6115d3f_1    conda-forge
r-evaluate                0.11             r341h6115d3f_0    conda-forge
r-fansi                   0.3.0            r341h6115d3f_0    conda-forge
r-forcats                 0.3.0            r341h6115d3f_1    conda-forge
r-foreach                 1.4.5                  mro343_0
r-foreign                 0.8_69                 mro343_0
r-forge                   0.1.0            r341h6115d3f_0    conda-forge
r-formatr                 1.5             mro343h889e2dd_0
r-fs                      1.2.6            r341h6115d3f_0    conda-forge
r-geometry                0.3_6            r341h6115d3f_2    conda-forge
r-ggplot2                 3.1.0            r341h6115d3f_0    conda-forge
r-gh                      1.0.1            r341h6115d3f_1    conda-forge
r-git2r                   0.23.0           r341hc0d41b1_0    conda-forge
r-glmnet                  2.0_16           r341h6115d3f_1    conda-forge
r-glue                    1.3.0            r341h301d43c_2    conda-forge
r-gower                   0.1.2           mro343h889e2dd_0
r-gtable                  0.2.0           mro343h889e2dd_0
r-haven                   1.1.2            r341h6115d3f_2    conda-forge
r-hexbin                  1.27.2           r341h6115d3f_2    conda-forge
r-highr                   0.7              r341h6115d3f_1    conda-forge
r-hms                     0.4.2            r341h6115d3f_0    conda-forge
r-htmltools               0.3.6           mro343h889e2dd_0
r-htmlwidgets             1.2              r341h6115d3f_0    conda-forge
r-httpuv                  1.4.5            r341hca4a3dc_1    conda-forge
r-httr                    1.3.1           mro343h889e2dd_0
r-ini                     0.3.1            r341h6115d3f_1    conda-forge
r-ipred                   0.9_7            r341h6115d3f_1    conda-forge
r-irdisplay               0.6.2                    r341_0    conda-forge
r-irkernel                0.8.14                   r341_0    conda-forge
r-iterators               1.0.9                  mro343_0
r-jsonlite                1.5                    mro343_0
r-kernlab                 0.9_27           r341h6115d3f_0    conda-forge
r-kernsmooth              2.23_15                mro343_0
r-knitr                   1.20             r341h6115d3f_1    conda-forge
r-labeling                0.3                    r3.4.1_2
r-later                   0.7.3            r341h6115d3f_0    conda-forge
r-lattice                 0.20_35                mro343_0
r-lava                    1.6.3            r341h6115d3f_1    conda-forge
r-lazyeval                0.2.1           mro343h889e2dd_0
r-lubridate               1.7.4            r341h6115d3f_1    conda-forge
r-magic                   1.5_8            r341h6115d3f_0    conda-forge
r-magrittr                1.5                    r3.4.1_2
r-maps                    3.3.0            r341h6115d3f_2    conda-forge
r-markdown                0.8             mro343h889e2dd_0
r-mass                    7.3_47                 mro343_0
r-matrix                  1.2_12                 mro343_0
r-memoise                 1.1.0           mro343h889e2dd_0
r-mgcv                    1.8_22                 mro343_0
r-microsoftr              3.4.3.0097             mro343_0
r-mime                    0.5             mro343h889e2dd_0
r-miniui                  0.1.1.1          r341h6115d3f_0    conda-forge
r-modelmetrics            1.1.0           mro343h889e2dd_0
r-modelr                  0.1.2            r341h6115d3f_1    conda-forge
r-mongolite               1.4             mro343h889e2dd_0
r-munsell                 0.5.0            r341h6115d3f_1    conda-forge
r-nlme                    3.1_131                mro343_0
r-nnet                    7.3_12                 mro343_0
r-numderiv                2016.8_1        mro343h889e2dd_0
r-odbc                    1.1.3           mro343h889e2dd_0
r-openssl                 1.0.2            r341hef39adb_0    conda-forge
r-packrat                 0.4.9_3          r341h6115d3f_1    conda-forge
r-pbdzmq                  0.3_2                  r3.4.1_0    conda-forge
r-pillar                  1.3.0            r341h6115d3f_0    conda-forge
r-pkgbuild                1.0.2            r341h6115d3f_0    conda-forge
r-pkgconfig               2.0.2            r341h6115d3f_1    conda-forge
r-pkgload                 1.0.1            r341h6115d3f_0    conda-forge
r-pki                     0.1_5.1         mro343h889e2dd_0
r-plogr                   0.2.0            r341h6115d3f_1    conda-forge
r-plotly                  4.8.0            r341h6115d3f_0    conda-forge
r-pls                     2.7_0            r341h6115d3f_0    conda-forge
r-plyr                    1.8.4           mro343h889e2dd_0
r-png                     0.1_7                  mro343_0
r-prettyunits             1.0.2            r341h6115d3f_1    conda-forge
r-processx                3.2.0            r341h6115d3f_1    conda-forge
r-prodlim                 2018.04.18       r341h6115d3f_2    conda-forge
r-profvis                 0.3.4           mro343h889e2dd_0
r-promises                1.0.1            r341h6115d3f_0    conda-forge
r-ps                      1.1.0            r341h6115d3f_1    conda-forge
r-purrr                   0.2.5            r341h6115d3f_1    conda-forge
r-quantmod                0.4_13           r341h6115d3f_0    conda-forge
r-r2d3                    0.2.2            r341h6115d3f_0    conda-forge
r-r6                      2.2.2                  mro343_0
r-randomforest            4.6_14           r341h6115d3f_0    conda-forge
r-rappdirs                0.3.1           mro343h889e2dd_0
r-rbokeh                  0.6.3                  mro343_0
r-rcmdcheck               1.3.0            r341h6115d3f_0    conda-forge
r-rcolorbrewer            1.1_2                  r3.4.1_3
r-rcpp                    1.0.0            r341h6115d3f_0    conda-forge
r-rcpproll                0.3.0            r341h6115d3f_0    conda-forge
r-rcurl                   1.95_4.11        r341h6115d3f_3    conda-forge
r-readr                   1.1.1           mro343h889e2dd_0
r-readxl                  1.1.0            r341h6115d3f_2    conda-forge
r-recipes                 0.1.3            r341h6115d3f_1    conda-forge
r-recommended             3.4.3                  mro343_0
r-rematch                 1.0.1           mro343h889e2dd_0
r-remotes                 2.0.1            r341h6115d3f_0    conda-forge
r-repr                    0.17                     r341_0    conda-forge
r-reprex                  0.2.0            r341h6115d3f_1    conda-forge
r-reshape2                1.4.3           mro343h889e2dd_0
r-reticulate              1.10             r341h6115d3f_1    conda-forge
r-revoioq                 8.0.9                  mro343_0
r-revomods                11.0.0                 mro343_0
r-revoutilsmath           10.0.1                 mro343_0
r-rjava                   0.9_9           mro343h889e2dd_0
r-rjdbc                   0.2_5           mro343h889e2dd_0
r-rjsonio                 1.3_0                  r3.4.1_2
r-rlang                   0.3.0.1          r341h301d43c_0    conda-forge
r-rmarkdown               1.10             r341h6115d3f_1    conda-forge
r-robustbase              0.93_2           r341h6115d3f_0    conda-forge
r-rodbc                   1.3_15          mro343h889e2dd_0
r-roxygen2                6.1.0            r341h6115d3f_0    conda-forge
r-rpart                   4.1_11                 mro343_0
r-rprojroot               1.3_2            r341h6115d3f_1    conda-forge
r-rsconnect               0.8.8            r341h6115d3f_1    conda-forge
r-rsqlite                 2.1.1            r341h6115d3f_0    conda-forge
r-rstudioapi              0.7             mro343h889e2dd_0
r-runit                   0.4.26                 mro343_0
r-rvest                   0.3.2           mro343h889e2dd_0
r-scales                  1.0.0            r341h6115d3f_1    conda-forge
r-selectr                 0.4_1            r341h6115d3f_0    conda-forge
r-sessioninfo             1.1.0            r341h6115d3f_0    conda-forge
r-sfsmisc                 1.1_2            r341h6115d3f_0    conda-forge
r-shiny                   1.2.0                    r341_0    conda-forge
r-sourcetools             0.1.7            r341hca4a3dc_0    conda-forge
r-sparklyr                0.9.2            r341h6115d3f_0    conda-forge
r-spatial                 7.3_11                 mro343_0
r-squarem                 2017.10_1        r341h6115d3f_1    conda-forge
r-stringi                 1.2.4            r341h6115d3f_1    conda-forge
r-stringr                 1.3.1            r341h6115d3f_1    conda-forge
r-survival                2.41_3                 mro343_0
r-tibble                  1.4.2            r341h6115d3f_2    conda-forge
r-tidyr                   0.8.1            r341h6115d3f_2    conda-forge
r-tidyselect              0.2.4            r341h6115d3f_2    conda-forge
r-tidyverse               1.2.1           mro343h889e2dd_0
r-timedate                3043.102         r341h6115d3f_0    conda-forge
r-tinytex                 0.8              r341h6115d3f_0    conda-forge
r-ttr                     0.23_4           r341h6115d3f_0    conda-forge
r-usethis                 1.4.0            r341h6115d3f_0    conda-forge
r-utf8                    1.1.4            r341h6115d3f_0    conda-forge
r-uuid                    0.1_2           mro343h889e2dd_0
r-viridislite             0.3.0            r341h6115d3f_1    conda-forge
r-whisker                 0.3_2                  r3.4.1_2
r-withr                   2.1.2            r341h6115d3f_0    conda-forge
r-xfun                    0.3              r341h6115d3f_1    conda-forge
r-xml2                    1.2.0            r341h6115d3f_2    conda-forge
r-xopen                   1.0.0            r341h6115d3f_0    conda-forge
r-xtable                  1.8_3                 r341_1000    conda-forge
r-xts                     0.11_1           r341h6115d3f_0    conda-forge
r-yaml                    2.2.0            r341h6115d3f_1    conda-forge
r-zoo                     1.8_3            r341h6115d3f_0    conda-forge
rpy2                      2.9.3              py36r3.4.1_0    conda-forge
rstudio                   1.1.456          vc14h1ad3211_1  [vc14]
setuptools                40.6.2                   py36_0
six                       1.11.0                   py36_1
sqlite                    3.25.3               he774522_0
tzlocal                   1.5.1                    py36_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wheel                     0.32.3                   py36_0
wincertstore              0.2              py36h7fe50ca_0
xorg-kbproto              1.0.7             h301d43c_1002    conda-forge
xorg-libice               1.0.9             h301d43c_1004    conda-forge
xorg-libsm                1.2.3             h301d43c_1000    conda-forge
xorg-libx11               1.6.6             h301d43c_1000    conda-forge
xorg-libxau               1.0.8             h301d43c_1006    conda-forge
xorg-libxdmcp             1.1.2             h301d43c_1007    conda-forge
xorg-libxext              1.3.3             h301d43c_1004    conda-forge
xorg-libxrender           0.9.10            h301d43c_1002    conda-forge
xorg-renderproto          0.11.1            h301d43c_1002    conda-forge
xorg-xextproto            7.3.0             h301d43c_1002    conda-forge
xorg-xproto               7.0.31            h301d43c_1007    conda-forge
zlib                      1.2.11               h62dcd97_3
```
</details>
<br>

```
λ conda list conda
# Name                    Version                   Build  Channel
conda                     4.5.11                   py36_0
```

Was #61 not supposed to prevent installing two different versions on top of each other?

**Comment by jdblischak** [comment] 2018-11-27 21:39
> ...with both defaults and conda-forge in my channels and it still appears to install two different versions of R:

@dhirschfeld I was able to confirm that I have the same issue.

> Was #61 not supposed to prevent installing two different versions on top of each other?

PR #61 solved this problem for R 3.5.1 only. When I was doing some testing, even if mro-base 3.5.1 was installed, r-base 3.4.1 from conda-forge was the one that was erroneously installed (and not r-base 3.5.1).

My understanding is that because R 3.4.1 wasn't able to be built with the new compilers (https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/147), it did not receive any of the new changes introduced in #61 (with additional explanation in #46). I doubt it is even still possible to build an updated version of r-base 3.4.1 now that the pinning has been updated on conda-forge.

**Comment by mingwandroid** [comment] 2018-11-28 01:46
Pinging @msarahan. For AD defaults `conda-build` fixes these when we run `conda index`. We need to figure out how to run this for `conda-forge`, I think .. but Mike will know more.

**Comment by msarahan** [comment] 2018-11-28 22:41
That hotfix is something we apply using logic here: https://github.com/AnacondaRecipes/repodata-hotfixes/blob/master/r.py

Conveniently, we're working to give conda-forge the ability to do hotfixes.  We turned it on this morning, but there were some issues that required us to turn it off.  We plan on trying again tomorrow morning.  If you'd like to prepare the repodata patches before then, copy the desired changes from the link above into https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/master/recipe/gen_patch_json.py in a PR.  When that PR is merged, those patches will be in place.  The next index that happens (roughly every 20 min) will pick it up, and you'll see the changed repodata once we switch on the cloudflare redirect again.

**Comment by qins** [comment] 2019-01-09 07:05
`$ conda install bioconductor-methylkit`

> Fetching package metadata .........................
> Solving package specifications: .
> 
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - bioconductor-methylkit -> bioconductor-fastseg -> bioconductor-biobase >=2.40.0,<2.42.0 -> bioconductor-biocgenerics >=0.26.0,<0.28.0 -> r-base >=3.5.1,<3.5.2.0a0 -> _r-mutex 1.* anacondar_1
>   - mro-base
> Use "conda info <package>" to see the dependencies for each package.
> 

Uninstall mro-base, and bioconductor-methylkit can be installed.

**Comment by jdblischak** [comment] 2019-01-09 19:48
> Uninstall mro-base, and bioconductor-methylkit can be installed.

@qins This is the expected behavior. mro-base is not compatible with R packages in the conda-forge and bioconda channels.

**Comment by isuruf** [comment] 2024-06-25 01:09
MRO was dropped in defaults

**Closed by isuruf** 2024-06-25 01:09 UTC
