### ISSUE TITLE
Add {{ compiler('c') }} to runtime dependencies

### ISSUE THREAD

**Issue by johanneskoester** [conda-forge/r-base-feedstock#55] opened 2018-08-03 18:49 UTC
I think it might be a good idea to add `{{ compiler('c') }}` to the runtime dependencies of r-base. This way, we could ensure that people can install R packages from within R while getting a compatible build environment. This could solve problems like [this one](https://support.bioconductor.org/p/108808/#111643).

I know this is somehow an unusual move, but it is very common to manually install stuff in R and people are suprised when it does not work, which causes quite some trouble for e.g. the bioconductor community.

@mingwandroid @bgruening thoughts?

**Comment by mingwandroid** [comment] 2018-08-03 19:39
We might want to consider our approach to handling system library dependencies. The cdt packages used could be collected into a metapackage and we could add that. Most of them are X11 related though and cf has their own X11 packages.

**Comment by mingwandroid** [comment] 2018-08-03 20:29
Btw the defaults r adds the compilers.

**Comment by mtmorgan** [comment] 2018-08-15 11:27
Issues related to using standard R package installation commands (`install.packages()`; biocLite() ultimately calls install.packages()) causing problems when packages contain src/ code seem to be occurring on a more-or-less daily basis on the Bioconductor forum.

  https://support.bioconductor.org/p/
  https://support.bioconductor.org/p/112086/

Is the diagnosis (that the fault lies with using install.packages to install packages requiring compilation) correct? Is there a work-around? What about a long-term solution? If using install.packages can't be supported, then are the steps the conda distribution can take to make it clear that doing so is an error?

**Comment by bgruening** [comment] 2018-08-15 11:35
@mtmorgan a workaround is that your users do install bioconductor packages but add a compiler to it as well. For example like: `conda create --name deseq2 bioconductor-deseq2 gcc`

**Comment by jakirkham** [comment] 2018-10-21 01:04
Tangential: Would it make sense to do the same thing with Python for the same reason or no?

**Comment by mingwandroid** [comment] 2018-10-21 09:09
Please, no one install `gcc` anymore. It is long deprecated (or at least the AD defaults package is). If there's some better `gcc` you are referring to @bgruening then fair enough.

@mtmorgan, @jakirkham, @johanneskoester, @bgruening: I have half a plan to redirect `install.packages()` to first try to install it with `conda`. With the prevelance of `install.packages()` I don't see a better option at present. I believe RStudio does something this too so I'd need to ensure that works too. I would appreciate feedback. I would also appreciate someone else figuring out the `R` code as I'm fairly inexperienced with actually coding in R (I can hack something together at a push though).

**Comment by mingwandroid** [comment] 2018-10-21 10:36
> I'm not sure this is worth the effort and pain

IMHO reproducable data science makes this a *requirement* for AD. The way to get there is to improve coverage (a lot!) and the way to get there is to improve build-out speed. I will be investigating ways to split the dependency graph into groups that can be run in parallel and someone's fixing some locking issues that will make that work.

We are also thinking to finally use `noarch: generic` for these (yay) where possible and of course unifying the Windows layout allows `noarch: generic` there too.

Our goal is to provide a coverage level beyond 90% I of the most popular packages, maybe more.

> I was referring to a compiler stack

Yeah, but when people see package names in a conda install commadline they sometimes copy them and then run into trouble. We include the compilers in `r-base` too.

Even with this expecting end-users to compile stuff is a bit fraught and broken; sometimes they need system packages installed though in theory I could make a r-cdt-system-packages metapackage (maybe one for us that includes X11 and one for CF that does not) and these would include all the `SystemRequires` I can find, e.g. from `r-rgl` (minus X11 for CF!). Still there's no mention of X11 in here at all which is disappointing because for sure it's necessary.

```
SystemRequirements: OpenGL, GLU Library, XQuartz (on OSX), zlib (optional), libpng (>=1.2.9, optional), FreeType (optional), pandoc (>=1.14, needed for vignettes)
```

Having said that Rcpp seems to behave very well in this regard.

BTW, I've been digging into the X11 stuff from the P.O.V. or CF's R infra, and looking at r-rgl I see a large amount of system libraries being used. I thought the point of the X11 isolation was to avoid *any* need for these? If the custom X11 stack still sometimes requires end-users to run `yum` or `apt-get` then what advantages does it provide us with?

```
ldd /opt/conda/envs/r351cf/lib/R/library/rgl/libs/rgl.so
	linux-vdso.so.1 =>  (0x00007ffc8b363000)
	libgfortran.so.3 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../../libgfortran.so.3 (0x00007fe3107c3000)
	libGLU.so.1 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../../libGLU.so.1 (0x00007fe310522000)
	libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007fe310299000)
	libpng16.so.16 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../../libpng16.so.16 (0x00007fe310058000)
	libX11.so.6 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../../libX11.so.6 (0x00007fe30fcf0000)
	libfreetype.so.6 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../../libfreetype.so.6 (0x00007fe30fa11000)
	libR.so => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../lib/libR.so (0x00007fe30f36f000)
	libstdc++.so.6 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../../libstdc++.so.6 (0x00007fe30f035000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe30edb1000)
	libgcc_s.so.1 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../../libgcc_s.so.1 (0x00007fe30eb9f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe30e80b000)
	libglapi.so.0 => /usr/lib64/libglapi.so.0 (0x00007fe30e5dd000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fe30e3be000)
	libXext.so.6 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../../libXext.so.6 (0x00007fe30e1a9000)
	libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x00007fe30dfa7000)
	libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007fe30dda2000)
	libX11-xcb.so.1 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../../libX11-xcb.so.1 (0x00007fe30dba1000)
	libxcb-glx.so.0 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../../libxcb-glx.so.0 (0x00007fe30d982000)
	libxcb-dri2.so.0 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../../libxcb-dri2.so.0 (0x00007fe30d77d000)
	libxcb.so.1 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../../libxcb.so.1 (0x00007fe30d54d000)
	libXxf86vm.so.1 => /usr/lib64/libXxf86vm.so.1 (0x00007fe30d348000)
	libdrm.so.2 => /usr/lib64/libdrm.so.2 (0x00007fe30d13b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe30cf1e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fe30cd1a000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007fe30caf2000)
	libz.so.1 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../.././libz.so.1 (0x00007fe30c8d5000)
	libRblas.so => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../lib/./libRblas.so (0x00007fe30c694000)
	libquadmath.so.0 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../lib/../../libquadmath.so.0 (0x00007fe30c463000)
	libreadline.so.7 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../lib/../../libreadline.so.7 (0x00007fe30c20f000)
	libpcre.so.1 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../lib/../../libpcre.so.1 (0x00007fe30bfbe000)
	liblzma.so.5 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../lib/../../liblzma.so.5 (0x00007fe30bd8b000)
	libbz2.so.1.0 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../lib/../../libbz2.so.1.0 (0x00007fe30bb7b000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fe30b973000)
	libiconv.so.2 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../lib/../../libiconv.so.2 (0x00007fe30b684000)
	libicuuc.so.58 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../lib/../../libicuuc.so.58 (0x00007fe30b285000)
	libicui18n.so.58 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../lib/../../libicui18n.so.58 (0x00007fe30ad85000)
	libgomp.so.1 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../lib/../../libgomp.so.1 (0x00007fe30ab62000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe310d99000)
	libXau.so.6 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../.././libXau.so.6 (0x00007fe30a95f000)
	libXdmcp.so.6 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../.././libXdmcp.so.6 (0x00007fe30a759000)
	libncurses.so.6 => /opt/conda/envs/r351cf/lib/libncurses.so.6 (0x00007fe30a52d000)
	libtinfo.so.6 => /opt/conda/envs/r351cf/lib/libtinfo.so.6 (0x00007fe30a2ef000)
	libicudata.so.58 => /opt/conda/envs/r351cf/lib/R/library/rgl/libs/../../../lib/../.././libicudata.so.58 (0x00007fe3087ef000
```

**Comment by bgruening** [comment] 2018-10-21 12:52
> IMHO reproducable data science makes this a requirement for AD. The way to get there is to improve coverage (a lot!) and the way to get there is to improve build-out speed. I will be investigating ways to split the dependency graph into groups that can be run in parallel and someone's fixing some locking issues that will make that work.

I totally agree with you here! But I'm skeptical we can reach 90% coverage anytime soon. CF maintains >1000 packages already, but this is by far not everything. AD is here a lot behind I think. 

But even if we manage to have such good coverage it is more about expectation management and communication. I questioning that people that use `install.packages()` care that much about reproducibility, I guess the primary use-case is to get the latest stuff from the primary repos. Redirecting `install.packages()` might not be what users expect.

Let's get the compilers in as you have it in AD as a first step and most of our users are probably fine with that. I would still like to see a r-base-like pkg without compilers for all automatic systems that rely on conda soley and do not need compilers.

**Comment by mingwandroid** [comment] 2018-10-21 12:59
> Redirecting install.packages() might not be what users expect.

I really don't think many would care. From R's perspective we install libraries 'correctly', so this would just mean that, when possible, conda *also* knows about them and for those who want to export conda envs we improve reproducibility somewhat at least. Unless we can prove real harm from this approach (which as I noted I've been told RStudio decided to take) I still plan look into it, probably initially hidden behind an env. var though for a testing period.

Can you explain the use case for an `r-base` without a compiler? I don't quite get that one; sure you could build R packages that do not need compilation on them and it would save a little time creating the build-env, is that the goalds of an such an `r-base`?

**Comment by mingwandroid** [comment] 2018-10-21 13:07
> I guess the primary use-case is to get the latest stuff from the primary repos. Redirecting install.packages() might not be what users expect

Hmm, not really, `install.packages()` is very nuanced. The latest packages on Windows and macOS will be fetched as binaries (except for MRO due to lots of binary incompatibilities - this is an MS customization that I cannot change until MRO is built to be inline with the upstream R). The binaries are only rebuilt at specific release check-point dates on CRAN which is not really any different from us. 

For other OSes it will download the latest source .. but I see no reason that cannot be supported via hooking to `conda skeleton` [*], `conda-build` in the `base` env with an error message to install that if it's not present when someone explicitly requests to install from source.

On top of all this I would try to make sure it is both informative and has graceful falls-backs to the normal behaviour.

**Comment by bgruening** [comment] 2018-10-21 13:35
Could we not issue a warning if `install.packages()` is used __and__ `r` is not installed? `r` would install the compilers. I have always considered `r-base` as lightweight and `r` as the batteries-included solution.

**Comment by mingwandroid** [comment] 2018-10-21 13:40
I don't ever install `r` and nothing ever depends upon it. It installs `r-base` and `r-recommended` but since our deps always tunnel through to the packages and versions that are actually needed this is something I can do without worry.

None of our messaging talks about `conda install r` anymore and I wouldn't like to have to change all that on the internet! My battle against `-c anaconda` has been challenging enough and has taught me that once stuff gets out there, it's difficult to turn the boat around.

**Comment by mingwandroid** [comment] 2018-10-21 13:41
We explicitly recommend: `conda-install r-base` or `conda-install mro-base` now.

**Comment by mingwandroid** [comment] 2018-10-21 13:44
> Could we not issue a warning if install.packages() is used and r is not installed?

Why not cut straight to the chase and issue a warning if the compilers themselves are not installed (and the package or its recursive, to-be-build dependencies require them as detected via `NeedsCompilation`)?

I do worry I'm may be signing myself up for a lot of R programming here than I'm comfortable with. Any R language experts here I can call upon for reviews when I get to that stage?

**Comment by isuruf** [comment] 2018-11-12 21:12
compilers are added for new compilers build

**Closed by isuruf** 2018-11-12 21:12 UTC
